version: '2'
services:
  desktop:
    build: .
#    image: 'consol/ubuntu-xfce-vnc:latest'
    ports:
      - '5901:5901'
      - '6901:6901'
    volumes:
      - './home/:/home/'
    environment:
      - VNC_PW=mipass
