version: '2'
services:
  desktop:
    image: 'albertalvarezbruned/ubuntu-vnc-light:latest'
    ports:
      - '5901:5901'
      - '6901:6901'
    volumes:
      - './home/:/home/'
    environment:
      - VNC_PW=mipass
#    command: sh /root/scripts/java_install_8.sh
#    command: sh /root/scripts/bluej_install.sh
#    command: sh /root/scripts/scribus.sh
#    command: sh /root/scripts/krita.sh
#    command: sh /root/scripts/netbeans_8_install.sh
