version: '2'
services:
  desktop:
    image: 'albertalvarezbruned/ubuntu-vnc-light:latest'
    ports:
      - '5901:5901'
      - '6901:6901'
    volumes:
      - './home/:/home/'
    environment:
      - VNC_PW=mipass
#    command: sh /home/java_install_8.sh
#    command: sh /home/bluej_install.sh
#    command: sh /home/netbeans_8_install.sh
